### ISSUE TITLE
Tables with 1 Entry Return Record Count of 0

### ISSUE THREAD

**Issue by yymax** [libyal/libesedb#17] opened 2016-02-24 19:04 UTC
Hi, Joachim 

First of all, thanks for open sourcing this wonderful ESE parser! I am currently building a WebCache parser using your ESE module, everything looks good except occasionally the module returns a record count of 0 for tables with only 1 record. I have attached a sample WebCahce file below where Container_30 and LeakFiles both return a count of 0, but using tools like ESEDatabaseViewer reveal they actually contain 1 record. 

[WebCacheV01_RecordCountIssue.zip](https://github.com/libyal/libesedb/files/145241/WebCacheV01_RecordCountIssue.zip)

Thanks,
Calvin

**Comment by joachimmetz** [comment] 2016-02-24 20:21
Thanks for the report. I'll have a look if time permits.

**Comment by dnides** [comment] 2017-05-09 15:25
@joachimmetz I know you are busy but any chance of taking a look at this in near future? We have come across numerous instances where data is missed because of this, but other tools like ESEDatabaseViewer  and IEF parse out.

**Comment by joachimmetz** [comment] 2017-05-10 05:55
@dnides when time permits, which is limited at the moment

this seems to be a duplicate of: https://github.com/libyal/libesedb/issues/11

**Comment by dnides** [comment] 2018-01-18 07:42
Saw you been working on this lib recently. If you have time to revisit this issue if he greatly appreciated. Thank you

**Comment by joachimmetz** [comment] 2018-01-18 08:12
When time permits, I have a very busy schedule.

**Comment by joachimmetz** [comment] 2018-12-28 11:10
According to the debug output the Container_30 table contains 1 defunct value:
```
libfdata_vector_get_element_value_by_index: cache: 0x00e2ec10 hit
libesedb_page_tree_read_page: page value: 001 page tag flags            : 0x03 (dv)
libesedb_page_tree_read_page: page value: 001 data:
00000000: 12 00 7f d0 3f d2 2c 38  62 eb 5b 7f 80 00 00 00   ....?.,8 b.[.....
00000010: 00 00 00 01 11 7f 77 00  01 00 00 00 00 00 00 00   ......w. ........
00000020: 1e 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000030: 5b eb 62 38 2c d2 3f 50  00 00 00 00 00 00 00 00   [.b8,.?P ........
00000040: 00 00 00 00 09 00 00 00  04 00 00 00 03 00 00 00   ........ ........
00000050: d6 d1 8e 44 a3 6d d1 01  00 00 00 00 00 00 00 00   ...D.m.. ........
00000060: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000070: d6 d1 8e 44 a3 6d d1 01  00 00 00 00 00 00 00 00   ...D.m.. ........
00000080: 00 00 00 00 00 00 00 00  00 00 fe 00 01 08 00 04   ........ ........
00000090: 01 6d 00 01 69 00 65 00  64 00 6f 00 77 00 6e 00   .m..i.e. d.o.w.n.
000000a0: 6c 00 6f 00 61 00 64 00  3a 00 7b 00 31 00 38 00   l.o.a.d. :.{.1.8.
000000b0: 31 00 35 00 43 00 46 00  30 00 36 00 2d 00 44 00   1.5.C.F. 0.6.-.D.
000000c0: 39 00 39 00 36 00 2d 00  31 00 31 00 45 00 35 00   9.9.6.-. 1.1.E.5.
000000d0: 2d 00 42 00 46 00 39 00  43 00 2d 00 30 00 30 00   -.B.F.9. C.-.0.0.
000000e0: 30 00 35 00 39 00 41 00  33 00 43 00 37 00 41 00   0.5.9.A. 3.C.7.A.
000000f0: 30 00 30 00 7d 00 00 00  05 03 00 00 00            0.0.}... .....
```

Marking as duplicate of #11

**Closed by joachimmetz** 2018-12-28 11:10 UTC
