### ISSUE TITLE
esedbexport: getting killed

### ISSUE THREAD

**Issue by piterjoin** [libyal/libesedb#3] opened 2014-10-11 15:08 UTC
When I execute a command: / root / Desktop / libesedb-20120102 / esedbtools / esedbexport /root/Desktop/ntds.dit

It returns the error message：
esedbexport 20120102

Opening file.
Exporting table 1 (MSysObjects) out of 11.
Exporting table 2 (MSysObjectsShadow) out of 11.
Exporting table 3 (MSysUnicodeFixupVer2) out of 11.
Exporting table 4 (datatable) out of 11.
Unable to export file.
libuna_unicode_character_copy_from_utf8: invalid 1st UTF-8 character byte: 0x80.
libuna_utf8_string_size_from_utf8_stream: unable to copy Unicode character from UTF-8 stream.
libfvalue_value_get_utf8_string_size: unable to determine UTF-8 string size of UTF-8 stream for codepage 1200.
libesedb_record_get_value_utf8_string_size: unable retrieve UTF-8 string size.
export_handle_export_record_value: unable to retrieve size of value string: 25 (271).
export_handle_export_record: unable to export record value: 25.
export_handle_export_table: unable to export record.
export_handle_export_file: unable to export table: 3.
# 

version:20140803
run:esedbexport -t /root/Desktop/ntds.dit /root/Desktop/ntds.dit 
return:
Opening file.
Exporting table 1 (MSysObjects) out of 11.
Exporting table 2 (MSysObjectsShadow) out of 11.
Exporting table 3 (MSysUnicodeFixupVer2) out of 11.
Exporting table 4 (datatable) out of 11.
kiiled

**Comment by misterfitzy** [comment] 2016-03-05 22:06
There's a savage memory leak in the master release of this tool.  Crashes with a 73MB ntdis.dit.  Tried it on 32bit and 64 bit Linux and also on Debian and CentOS.  If I get a chance I'll see if I can fix this over the weekend.

**Comment by misterfitzy** [comment] 2016-03-05 22:18
Version: 20151213 works fine.

**Comment by joachimmetz** [comment] 2016-03-06 08:02
@misterfitzy can you be more specific and add some facts to back up your claims e.g. valgrind log. So the issues can be fixed.

**Comment by ClevererBoy** [comment] 2016-03-24 18:47
My scenario:
Kali
299MB ntdis.dit
8GB RAM
Gets killed during exporting of table 5 (database).  
Anything I can do to help t-shoot or workaround?

**Comment by joachimmetz** [comment] 2018-12-28 08:10
Lack of necessary input from the reporter. Closing issue as unable to reproduce.

**Closed by joachimmetz** 2018-12-28 08:10 UTC
Labels: bug
