### ISSUE TITLE
Slow Extraction of Tables

### ISSUE THREAD

**Issue by LSD4me** [libyal/libesedb#8] opened 2015-02-11 18:57 UTC
Hey,

First off, great work in keeping this updated!

My issue is with the extraction speed of a 1.3 GB NTDS.dit file. I know you say this is not intended for large +1 GB databases, but the speed at which it extracts is DOG SLOW....it would takes weeks on end for this to extract the datatable.

When using the original 2012 alpha version , the extraction is SUPER FAST, however, it crashes half way through; consistently.

When trying to use the updated version (git), it doesn't crash but the extraction is so slow it prevents any type of conclusion.

Is there something I need to be doing differently to extract the tables faster? 

I am on a CentOS 6 distro with 8 CPU and 16 GB RAM.

Thanks!

**Comment by joachimmetz** [comment] 2015-02-11 19:54
duplicate of  https://github.com/libyal/libesedb/issues/2

**Closed by joachimmetz** 2015-02-11 19:54 UTC
Labels: duplicate

**Comment by LSD4me** [comment] 2015-02-11 20:44
My issue is not with 10+ GB....Its a 1 GB file...

**Comment by joachimmetz** [comment] 2015-02-11 20:45
yes I understand; its the same issue though: the library does not handle large databases well.

**Comment by LSD4me** [comment] 2015-02-11 20:47
Understood....

**Comment by LSD4me** [comment] 2015-02-12 16:15
For anyone else with the same slow extraction issue, I was able to resolve my problem using the release with version (esedbexport 20140406)

Extraction was fast and there was no 1200 errors....

Just an FYI

**Comment by joachimmetz** [comment] 2015-02-12 17:03
Yes the matter of fact is that the git version is marked as experimental and 20140406 as alpha.

**Comment by LSD4me** [comment] 2015-02-12 17:19
Either way, i thank you again for your efforts with keeping this project updated.

**Comment by joachimmetz** [comment] 2015-02-12 17:31
That will be on and off since have little available time to work on it.

**Comment by wintermute4316** [comment] 2015-07-30 12:38
Oh man I wish I had found this post 2 days ago.  I have a very large ntds.dit file (30+GB) to process.  I started with the latest version of libesedb straight from the repository (git clone = esedbexport 20150703) and I left esedbexport running overnight about 8-9 hours and it was still on the datatable.4 file at about 150k only!  Extremely slow and would have taken months to extract.

Then I tried one of the release versions linked to on the Github repo (libesedb-experimental-20141110.tar.gz), compiled it and left it running overnight and the datatable.4 file was at about 6MB and still going.  Better, but still too slow to finish in feasible time.

Then I found this article and Googled for version libesedb-experimental-20140406.tar.gz and tried this one.  What a difference and in just a couple of minutes datatable.4 was already up to a 6MB.  You should include this version as one of your releases because it is extremely fast compared to the others you have.  I found a mirror at this link: https://archive-master.linux.bfh.ch/files/old/reprepro.its.bfh.ch/archive-master/releases/wheezy/packages.orig/libesedb/other/libesedb-experimental-20140406.tar.gz

Hope this helps anyone else having this issue with a very large ntds.dit file and saves you some time.

**Comment by joachimmetz** [comment] 2015-07-30 12:50
@wintermute4316 stop spamming closed bugs.

> started with the latest version of libesedb straight from the repository

What part of "experimental" don't you understand ?

**Comment by krystian1313** [comment] 2016-08-04 14:04
Hi,

Same issue here, running 2-3 GB databases will make the latest version run for weeks and weeks (kind of like that Duracell bunny).

Kind Regards
K

**Comment by 9Yg1rxeSeha90ZU1** [comment] 2016-09-08 15:40
https://www.swordshield.com/2015/10/extracting-password-hashes-from-large-ntds-dit-files/

**Comment by joachimmetz** [comment] 2016-09-08 19:18
It very nice that everyone is complaining about this but I see no contributions in terms of fixes?

**Comment by krystian1313** [comment] 2016-09-08 19:25
Joachim, if I could code I would :)
btw Ive seen the article, for us the fastest way was to compile it under linux, there it works, but we would prefer windows build.

Speaking of sollutions I can ask my guys to tell or post here their experience, maybe we can point you in the right direction at least?

**Comment by joachimmetz** [comment] 2016-09-08 19:28
The problem is that people are using an experimental piece of code for purposes it was not designed for and the only thing I get is people complaining. Without taking the decency to reach out and offer help to fix it. Apparently this is how you say thanks of putting the source out there in the field of pentesting.

**Comment by 9Yg1rxeSeha90ZU1** [comment] 2016-09-08 19:36
@joachimmetz -- was just pointing out that the quickest solution to the slowness problem appears to be to utilize secretsdump.py instead if just seeking password hashes. It was in no way a complaint. And perhaps we can take a look at the code sometime to discover a workaround later, if necessary. do you have any idea why it is slow? have you traced the code on a file input that demonstrates the slowness?

**Comment by krystian1313** [comment] 2016-09-08 19:36
Ah there is missmatch here Joachim. The only feeling I have is gratitude as this is giving every Win pentester an important tool.

To be fair when we downloaded it we had little idea what is official or what experimental. The code is far too big and complex for my guys to look at it in their time between jobs, hence why we dont commit.

What we do have is data in which this code behaves differently than anticipated and can help with testing out different versions to see how they work, maybe even code if we knew where to look (although i cannor make promises).

Any ideas which versions are fast/slow, where the issue lies?

**Comment by joachimmetz** [comment] 2016-09-08 19:52
Reach out if things are not clear. The info is there, the issues are there.

There is this magical thinking that any given project is going to solve your problem. If you don't check if the project actually addresses your problem you'll run into surprises it is part on a normal software selection process.

This library was not build with pentesting in mind, nor with reading full size exchange databases.

> The code is far too big and complex for my guys to look at it in their time between jobs, hence why we dont commit.

Do you think I have the timeof the world  to work on this?
