### ISSUE TITLE
The results of the analysis are different

### ISSUE THREAD

**Issue by siten** [libyal/libesedb#28] opened 2017-06-28 08:36 UTC
The same edb file
![esedatabaseview](https://user-images.githubusercontent.com/3325638/27627765-8a1867dc-5c1f-11e7-809e-6f53fdc5b188.png)
![libesedb](https://user-images.githubusercontent.com/3325638/27627777-986d3e7a-5c1f-11e7-85a8-8d6a3defed8b.png)

The results are different. 
ESEDatabaseView download : http://www.nirsoft.net/utils/ese_database_view.html

Thank you.

**Comment by joachimmetz** [comment] 2017-06-28 19:05
are the additional result recovered records?

**Comment by siten** [comment] 2017-06-29 00:42
Okay, thank you so much

**Comment by siten** [comment] 2017-06-29 00:44
I do not know much about this format. thanks

**Comment by joachimmetz** [comment] 2018-12-28 10:32
Unable to confirm or deny claims without test data. Closing issue, reopen if the test file can be shared. Otherwise assuming duplicate of https://github.com/libyal/libesedb/issues/17.

**Closed by joachimmetz** 2018-12-28 10:32 UTC
Labels: question
