### ISSUE TITLE
Extraction of huge database is very very slow !

### ISSUE THREAD

**Issue by jackpit110** [libyal/libesedb#42] opened 2018-07-21 06:15 UTC
Hi 
First I want to thanks for this great project
At this time i use this version : 20180716 and it is very slow and I think it tool more than a month to extract this huge database
I know impacket so please do not suggest this ! and also I read other issue but I did not get any useful response
So how should I speed up this extraction?

**Comment by joachimmetz** [comment] 2018-07-21 08:18
libesedb is currently designed for small databases.

Duplicate of: https://github.com/libyal/libesedb/issues/2.

**Comment by joachimmetz** [comment] 2018-07-21 08:19
> I know impacket so please do not suggest this ! and also I read other issue but I did not get any useful response

unclear to me what you mean

**Comment by joachimmetz** [comment] 2018-07-21 08:42
If by other issue you mean https://github.com/libyal/libesedb/issues/40

```
Duplicate of #34
```

means that the issue you reported was already reported and you should look at that issue for status updates. To set some expectations, the development of this project is best effort, if you expect immediate support/fixes, I suggest you hire someone to help you and contribute back to the project.

**Closed** 2018-10-11 18:07 UTC
Labels: duplicate, question
