### ISSUE TITLE
Issue with python library

### ISSUE THREAD

**Issue by ddurvaux** [libyal/libesedb#29] opened 2017-07-06 09:16 UTC
Dear,

I use the release "libesedb-experimental-20170121" and in particular, I'm trying to use the python library with Python 3.6.1 on Windows 10.

The python library seems empty (functions like file() are absent).

Test:
```python
import sys
sys.path.append("C:\\Tools\\libesedb-20170121\\")
import pyesedb

dir(pyesedb)
```

Result: `['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']`

**Comment by ddurvaux** [comment] 2017-07-06 11:14
The issue is actually related to Windows.  Same procedure for compilation and same code on Mac OS X gives another result

```
['__doc__', '__file__', '__name__', '__package__', '_columns', '_records', '_tables', 'check_file_signature', 'check_file_signature_file_object', 'column', 'column_types', 'file', 'get_version', 'long_value', 'multi_value', 'open', 'open_file_object', 'record', 'table', 'value_flags']
```

**Comment by joachimmetz** [comment] 2018-12-29 17:09
@ddurvaux I just tested this with the most recent version of pyesedb (20181229) on Windows with Python 3.6 64-bit on Windows 10 and I'm unable to reproduce this. I'll close this issue. Let me know if the issue persists for you, and I'll reopen this issue.

**Closed by joachimmetz** 2018-12-29 17:09 UTC
Labels: needs a closer look
