### ISSUE TITLE
Windows 2016 NTDS.dit problem

### ISSUE THREAD

**Issue by jackpit110** [libyal/libesedb#40] opened 2018-05-08 12:14 UTC
I can not export ntds.dit of windows server 2016

Unable to open: ../ntds.dit.
libesedb_catalog_definition_read: unsupported last fixed size data type: 12.
libesedb_catalog_read: unable to read catalog definition.
libesedb_file_open_read: unable to read catalog.
libesedb_file_open_file_io_handle: unable to read from file handle.
libesedb_file_open: unable to open file: ../ntds.dit.
info_handle_open: unable to open input file.

**Comment by joachimmetz** [comment] 2018-05-09 05:00
Duplicate of https://github.com/libyal/libesedb/issues/34

**Closed by joachimmetz** 2018-05-09 05:00 UTC
